let PAGE_INDEX=[];
const WATCH_KEY='gazetki.watchedProducts.v1';
const searchNorm=s=>(s||'').toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ł/g,'l').replace(/[^a-z0-9]+/g,' ').trim();
const searchTokens=q=>searchNorm(q).split(/\s+/).filter(x=>x.length>=2);
function textMatches(text,q){const hay=searchNorm(text),tokens=searchTokens(q);return !!tokens.length&&(hay.includes(searchNorm(q))||tokens.every(t=>hay.includes(t)))}
function loadWatches(){try{const x=JSON.parse(localStorage.getItem(WATCH_KEY));return Array.isArray(x)?x:[]}catch{return[]}}
function saveWatches(x){localStorage.setItem(WATCH_KEY,JSON.stringify([...new Set(x.map(v=>v.trim()).filter(Boolean))]));renderWatchPanel()}
function toggleWatch(q){q=q.trim();if(q.length<2)return;let w=loadWatches(),i=w.findIndex(x=>searchNorm(x)===searchNorm(q));if(i>=0)w.splice(i,1);else w.push(q);saveWatches(w);enhancedRenderProducts()}
function leafletFor(id,storeId){return LEAFLETS.find(x=>x.id===id)||LEAFLETS.find(x=>x.storeId===storeId)}
async function loadPageIndex(){try{const r=await fetch('./data/page-index.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();PAGE_INDEX=Array.isArray(d.pages)?d.pages:[]}catch{PAGE_INDEX=[]}enhancedRenderProducts();renderWatchPanel()}
function matchingProducts(q){return PRODUCTS.filter(x=>textMatches(`${x.name} ${x.category||''} ${x.store||''} ${x.conditions||''}`,q))}
function matchingPages(q){return PAGE_INDEX.filter(x=>textMatches(x.text,q))}
function cleanExcerpt(text,q){const words=(text||'').replace(/\s+/g,' ').trim().split(' '),tokens=searchTokens(q);let at=0;for(let i=0;i<words.length;i++){if(tokens.some(t=>searchNorm(words[i]).includes(t))){at=i;break}}const a=Math.max(0,at-5),b=Math.min(words.length,at+18);return `${a?'… ':''}${words.slice(a,b).join(' ')}${b<words.length?' …':''}`}
function pageTitle(q,h){const phrase=q.trim();return phrase.length?`${phrase.charAt(0).toLocaleUpperCase('pl')+phrase.slice(1)} — znalezione w gazetce`:`Oferta w gazetce`}
function watchHits(q){const prod=matchingProducts(q).map(p=>({...p,type:'product'}));const used=new Set(prod.map(p=>`${p.leafletId}:${p.page||1}`));const pages=matchingPages(q).filter(p=>!used.has(`${p.leafletId}:${p.page}`)).map(p=>{const l=leafletFor(p.leafletId,p.storeId);return {store:p.store,storeId:p.storeId,leafletId:p.leafletId,page:p.page,validFrom:l?.from,validTo:l?.to,imageUrl:p.imageUrl,type:'page'}});return [...prod,...pages]}
function statusFor(h){const t=todayISO();if(h.validFrom&&h.validFrom>t)return['soon','PROMOCJA WKRÓTCE'];if(!h.validTo||h.validTo>=t)return['now','W GAZETCE TERAZ'];return['none','BRAK AKTUALNEJ PROMOCJI']}
function renderWatchPanel(){let box=document.querySelector('#watchPanel');if(!box){const host=document.querySelector('#productsView .panel');if(!host)return;box=document.createElement('section');box.id='watchPanel';host.insertBefore(box,document.querySelector('#products'))}const watches=loadWatches();box.innerHTML=`<div class="watch-head"><div><h3>Moje obserwowane</h3><div class="muted">Tutaj zawsze widzisz, czy rzecz jest w aktualnej lub nadchodzącej gazetce.</div></div><span class="watch-count">${watches.length}</span></div><div class="watch-list"></div>`;const list=box.querySelector('.watch-list');if(!watches.length){list.innerHTML='<div class="watch-empty">Nic jeszcze nie obserwujesz. Wyszukaj rzecz i kliknij „Obserwuj”.</div>';return}for(const q of watches){const hits=watchHits(q);hits.sort((a,b)=>(a.validFrom||'9999').localeCompare(b.validFrom||'9999'));const best=hits.find(h=>h.validFrom&&h.validFrom>todayISO())||hits.find(h=>!h.validTo||h.validTo>=todayISO())||null;const [kind,label]=best?statusFor(best):['none','BRAK W AKTUALNYCH GAZETKACH'];const product=hits.find(h=>h.type==='product');const row=document.createElement('article');row.className=`watch-card watch-${kind}`;row.innerHTML=`<div class="watch-main"><div class="watch-name">${q}</div><span class="watch-status">${label}</span>${best?`<div class="watch-meta"><strong>${best.store}</strong>${best.validFrom?` • ${fmt(best.validFrom)}–${fmt(best.validTo)}`:''}</div>`:''}${product?`<div class="watch-product">${product.name}${Number.isFinite(product.price)?` • <strong>${money(product.price)}</strong>`:''}${product.package?` • ${product.package}`:''}</div>`:''}</div><div class="watch-actions">${best?'<button data-open>Pokaż ofertę</button>':''}<button class="secondary" data-remove>Usuń</button></div>`;row.querySelector('[data-open]')?.addEventListener('click',()=>{const l=leafletFor(best.leafletId,best.storeId);if(l)openViewer(l,best.page||1)});row.querySelector('[data-remove]').onclick=()=>toggleWatch(q);list.appendChild(row)}}
function renderProductCard(x,root){const d=document.createElement('article');d.className='product-card';d.innerHTML=`<div class="product-store">${x.store}</div><h3>${x.name}</h3><div class="product-price">${money(x.price)}</div>${x.regularPrice?`<div class="old-price">${money(x.regularPrice)}</div>`:''}<div class="muted">${x.package||'Oferta z gazetki'}</div><div class="promo-line">W GAZETCE • ${fmt(x.validFrom)}–${fmt(x.validTo)}</div><div class="product-actions"><button data-add>Dodaj do listy</button><button data-page class="secondary">Pokaż ofertę</button></div>`;d.querySelector('[data-add]').onclick=()=>addToCart(x.id);d.querySelector('[data-page]').onclick=()=>showProductLeaflet(x);root.appendChild(d)}
function renderPageHit(h,q,root){const leaf=leafletFor(h.leafletId,h.storeId);if(!leaf)return;const d=document.createElement('article');d.className='product-card ocr-result';d.innerHTML=`<img class="result-thumb" src="${h.imageUrl||leaf.pages?.[h.page-1]||''}" alt="Strona ${h.page} gazetki ${h.store}" loading="lazy"><div class="result-body"><div class="product-store">${h.store}</div><h3>${pageTitle(q,h)}</h3><div class="result-location">Strona ${h.page}</div><div class="result-excerpt">${cleanExcerpt(h.text,q)}</div><div class="promo-line">${leaf.from>todayISO()?'PROMOCJA WKRÓTCE':'W GAZETCE TERAZ'} • ${fmt(leaf.from)}–${fmt(leaf.to)}</div><button data-page>Pokaż stronę ${h.page}</button></div>`;d.querySelector('[data-page]').onclick=()=>openViewer(leaf,h.page);root.appendChild(d)}
function enhancedRenderProducts(){const input=document.querySelector('#productSearch');if(!input)return;const q=input.value.trim(),sort=document.querySelector('#productSort')?.value||'priceAsc';let a=q?matchingProducts(q):PRODUCTS.slice();a.sort((x,y)=>sort==='priceDesc'?y.price-x.price:sort==='unitAsc'?(x.unitPrice??999)-(y.unitPrice??999):sort==='store'?x.store.localeCompare(y.store,'pl'):x.price-y.price);let hits=[];if(searchTokens(q).length){const used=new Set(a.map(x=>`${x.leafletId}:${x.page||1}`));hits=matchingPages(q).filter(x=>!used.has(`${x.leafletId}:${x.page}`)).slice(0,30)}const info=document.querySelector('#productInfo'),root=document.querySelector('#products');const watched=q&&loadWatches().some(x=>searchNorm(x)===searchNorm(q));info.innerHTML=q?`${a.length} konkretnych ofert • ${hits.length} dodatkowych trafień w gazetkach <button id="watchSearch" class="secondary">${watched?'✓ Obserwujesz':'Obserwuj tę rzecz'}</button>`:`${a.length} rozpoznanych ofert. Wpisz nazwę produktu, aby przeszukać także wszystkie strony gazetek.`;document.querySelector('#watchSearch')?.addEventListener('click',()=>toggleWatch(q));root.innerHTML='';a.forEach(x=>renderProductCard(x,root));hits.forEach(h=>renderPageHit(h,q,root));if(q&&!a.length&&!hits.length)root.innerHTML='<div class="empty">Nie znaleziono tej rzeczy w aktualnych ani nadchodzących gazetkach. Kliknij „Obserwuj tę rzecz”, a pojawi się w panelu Moje obserwowane.</div>';renderWatchPanel()}
const css=document.createElement('style');css.textContent=`#watchPanel{margin:18px 0 6px;padding:18px;border:1px solid #dbeafe;border-radius:16px;background:#f8fbff}.watch-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.watch-head h3{margin:0 0 4px}.watch-count{min-width:30px;height:30px;display:grid;place-items:center;border-radius:999px;background:#2563eb;color:white;font-weight:900}.watch-list{display:grid;gap:10px;margin-top:14px}.watch-card{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:14px;border:1px solid #e5e7eb;border-left:5px solid #94a3b8;border-radius:12px;background:white}.watch-now{border-left-color:#059669}.watch-soon{border-left-color:#d97706}.watch-name{font-size:18px;font-weight:900}.watch-status{display:inline-block;margin:6px 0;padding:4px 8px;border-radius:999px;background:#ecfdf5;color:#047857;font-size:11px;font-weight:900}.watch-soon .watch-status{background:#fffbeb;color:#b45309}.watch-none .watch-status{background:#f1f5f9;color:#64748b}.watch-meta,.watch-product{margin-top:5px;font-size:13px}.watch-actions{display:flex;gap:7px}.watch-empty{padding:12px;color:#64748b}.ocr-result{padding:0;overflow:hidden;display:grid;grid-template-columns:145px 1fr}.result-thumb{width:145px;height:100%;min-height:210px;object-fit:cover;object-position:top;background:#f1f5f9}.result-body{padding:15px;display:grid;gap:9px}.result-location{font-size:13px;font-weight:800;color:#475569}.result-excerpt{font-size:13px;line-height:1.45;color:#64748b;max-height:58px;overflow:hidden}@media(max-width:650px){.watch-card{align-items:flex-start;flex-direction:column}.watch-actions{width:100%}.watch-actions button{flex:1}.ocr-result{grid-template-columns:95px 1fr}.result-thumb{width:95px;min-height:190px}.result-excerpt{display:none}}`;document.head.appendChild(css);
const productSearch=document.querySelector('#productSearch'),productSort=document.querySelector('#productSort');if(productSearch)productSearch.oninput=enhancedRenderProducts;if(productSort)productSort.onchange=enhancedRenderProducts;loadPageIndex();