let PAGE_INDEX=[];
const WATCH_KEY='gazetki.watchedProducts.v2',OLD_WATCH_KEY='gazetki.watchedProducts.v1',OCR_CART_KEY='gazetki.ocrCartProducts.v1';
const searchNorm=s=>(s||'').toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ł/g,'l').replace(/[^a-z0-9]+/g,' ').trim();
const searchTokens=q=>searchNorm(q).split(/\s+/).filter(x=>x.length>=2);
function textMatches(text,q){const hay=searchNorm(text),tokens=searchTokens(q);return !!tokens.length&&(hay.includes(searchNorm(q))||tokens.every(t=>hay.includes(t)))}
function leafletFor(id,storeId){return LEAFLETS.find(x=>x.id===id)||LEAFLETS.find(x=>x.storeId===storeId)}
function loadWatches(){try{const v2=JSON.parse(localStorage.getItem(WATCH_KEY));if(Array.isArray(v2))return v2}catch{}try{const old=JSON.parse(localStorage.getItem(OLD_WATCH_KEY));if(Array.isArray(old)){const migrated=old.map(q=>({id:'query:'+searchNorm(q),type:'query',query:q,label:q}));localStorage.setItem(WATCH_KEY,JSON.stringify(migrated));return migrated}}catch{}return[]}
function saveWatches(w){localStorage.setItem(WATCH_KEY,JSON.stringify(w));renderWatchPanel()}
function isWatched(id){return loadWatches().some(w=>w.id===id)}
function toggleWatchItem(item){let w=loadWatches(),i=w.findIndex(x=>x.id===item.id);if(i>=0)w.splice(i,1);else w.push(item);saveWatches(w);enhancedRenderProducts()}
function queryWatch(q){return{id:'query:'+searchNorm(q),type:'query',query:q,label:q}}
function productWatch(p){const l=leafletFor(p.leafletId,p.storeId);return{id:'product:'+p.id,type:'product',query:p.name,label:p.name,store:l?.store||p.store,storeId:l?.storeId||p.storeId,leafletId:l?.id||p.leafletId,page:p.page||1,price:p.price,package:p.package||'',validFrom:l?.from||p.validFrom,validTo:l?.to||p.validTo}}
function pageWatch(h,q){const l=leafletFor(h.leafletId,h.storeId);return{id:`page:${h.leafletId}:${h.page}:${searchNorm(q)}`,type:'page',query:q,label:q,store:l?.store||h.store,storeId:l?.storeId||h.storeId,leafletId:l?.id||h.leafletId,page:h.page,validFrom:l?.from,validTo:l?.to}}
function removeWatch(id){saveWatches(loadWatches().filter(w=>w.id!==id));enhancedRenderProducts()}
function matchingProducts(q){return PRODUCTS.filter(x=>textMatches(`${x.name} ${x.category||''} ${x.store||''} ${x.conditions||''}`,q))}
function matchingPages(q){return PAGE_INDEX.filter(x=>textMatches(x.text,q))}
function allHits(q){return{products:matchingProducts(q),pages:matchingPages(q)}}
function cleanExcerpt(text,q){const words=(text||'').replace(/\s+/g,' ').trim().split(' '),tokens=searchTokens(q);let at=0;for(let i=0;i<words.length;i++)if(tokens.some(t=>searchNorm(words[i]).includes(t))){at=i;break}const a=Math.max(0,at-5),b=Math.min(words.length,at+18);return `${a?'… ':''}${words.slice(a,b).join(' ')}${b<words.length?' …':''}`}
function restoreOcrProducts(){try{const arr=JSON.parse(localStorage.getItem(OCR_CART_KEY));if(Array.isArray(arr))for(const p of arr)if(!PRODUCTS.some(x=>x.id===p.id))PRODUCTS.push(p)}catch{}}
function saveOcrProduct(p){let arr=[];try{arr=JSON.parse(localStorage.getItem(OCR_CART_KEY))||[]}catch{}if(!arr.some(x=>x.id===p.id))arr.push(p);localStorage.setItem(OCR_CART_KEY,JSON.stringify(arr));if(!PRODUCTS.some(x=>x.id===p.id))PRODUCTS.push(p)}
function addPageHitToCart(h,q){const l=leafletFor(h.leafletId,h.storeId);if(!l)return;const id=`ocr-${h.leafletId}-${h.page}-${searchNorm(q).replace(/ /g,'-')}`;const p={id,name:q.trim(),store:l.store,storeId:l.storeId,price:null,regularPrice:null,unit:'gazetka',package:`Gazetka, strona ${h.page}`,leafletId:l.id,page:h.page,validFrom:l.from,validTo:l.to,ocr:true};saveOcrProduct(p);addToCart(id)}
async function loadPageIndex(){try{const r=await fetch('./data/page-index.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();PAGE_INDEX=Array.isArray(d.pages)?d.pages:[]}catch{PAGE_INDEX=[]}restoreOcrProducts();enhancedRenderProducts();renderWatchPanel()}
function renderWatchPanel(){let box=document.querySelector('#watchPanel');if(!box){const host=document.querySelector('#productsView .panel');if(!host)return;box=document.createElement('section');box.id='watchPanel';host.insertBefore(box,document.querySelector('#products'))}const watches=loadWatches();box.innerHTML=`<div class="watch-head"><div><h3>Moje obserwowane</h3><div class="muted">Możesz obserwować całą frazę albo wybraną konkretną ofertę.</div></div><span class="watch-count">${watches.length}</span></div><div class="watch-list"></div>`;const list=box.querySelector('.watch-list');if(!watches.length){list.innerHTML='<div class="watch-empty">Nic jeszcze nie obserwujesz.</div>';return}for(const w of watches){const row=document.createElement('article');row.className='watch-card';if(w.type==='query'){const hits=allHits(w.query),stores=new Set([...hits.products.map(p=>leafletFor(p.leafletId,p.storeId)?.store||p.store),...hits.pages.map(p=>leafletFor(p.leafletId,p.storeId)?.store||p.store)].filter(Boolean));row.innerHTML=`<div class="watch-main"><div class="watch-name">${w.label}</div><span class="watch-status">OBSERWUJESZ FRAZĘ</span><div class="watch-meta">${hits.products.length} konkretnych ofert • ${hits.pages.length} trafień na stronach • ${stores.size} sklepów</div><div class="muted">Nie wybieramy produktu za Ciebie. Otwórz wyniki i wskaż konkretną ofertę, jeśli chcesz.</div></div><div class="watch-actions"><button data-results>Pokaż wyniki</button><button class="secondary" data-remove>Usuń</button></div>`;row.querySelector('[data-results]').onclick=()=>{document.querySelector('#productSearch').value=w.query;enhancedRenderProducts();document.querySelector('#products').scrollIntoView({behavior:'smooth'})}}else{const l=leafletFor(w.leafletId,w.storeId),store=l?.store||w.store;row.innerHTML=`<div class="watch-main"><div class="watch-name">${w.label}</div><span class="watch-status">KONKRETNA OFERTA</span><div class="watch-meta"><strong>${store}</strong>${l?` • ${fmt(l.from)}–${fmt(l.to)} • strona ${w.page}`:''}</div>${Number.isFinite(w.price)?`<div class="watch-product"><strong>${money(w.price)}</strong>${w.package?` • ${w.package}`:''}</div>`:''}</div><div class="watch-actions"><button data-open>Pokaż ofertę</button><button class="secondary" data-remove>Usuń</button></div>`;row.querySelector('[data-open]').onclick=()=>{if(l)openViewer(l,w.page||1)}}row.querySelector('[data-remove]').onclick=()=>removeWatch(w.id);list.appendChild(row)}}
function renderProductCard(x,root){const l=leafletFor(x.leafletId,x.storeId),w=productWatch(x),watched=isWatched(w.id),d=document.createElement('article');d.className='product-card';d.innerHTML=`<div class="product-store">${l?.store||x.store}</div><h3>${x.name}</h3><div class="product-price">${Number.isFinite(x.price)?money(x.price):'Cena w gazetce'}</div>${x.regularPrice?`<div class="old-price">${money(x.regularPrice)}</div>`:''}<div class="muted">${x.package||'Oferta z gazetki'}</div><div class="promo-line">W GAZETCE • ${fmt(l?.from||x.validFrom)}–${fmt(l?.to||x.validTo)}</div><div class="product-actions three"><button data-add>+ Lista zakupów</button><button data-watch class="secondary">${watched?'★ Obserwujesz':'☆ Obserwuj ofertę'}</button><button data-page class="secondary">Pokaż ofertę</button></div>`;d.querySelector('[data-add]').onclick=()=>addToCart(x.id);d.querySelector('[data-watch]').onclick=()=>toggleWatchItem(w);d.querySelector('[data-page]').onclick=()=>showProductLeaflet(x);root.appendChild(d)}
function renderPageHit(h,q,root){const leaf=leafletFor(h.leafletId,h.storeId);if(!leaf)return;const w=pageWatch(h,q),watched=isWatched(w.id),d=document.createElement('article');d.className='product-card ocr-result';d.innerHTML=`<img class="result-thumb" src="${h.imageUrl||leaf.pages?.[h.page-1]||''}" alt="Strona ${h.page} gazetki ${leaf.store}" loading="lazy"><div class="result-body"><div class="product-store">${leaf.store}</div><h3>${q.charAt(0).toLocaleUpperCase('pl')+q.slice(1)} — znalezione w gazetce</h3><div class="result-location">Strona ${h.page}</div><div class="result-excerpt">${cleanExcerpt(h.text,q)}</div><div class="promo-line">${leaf.from>todayISO()?'PROMOCJA WKRÓTCE':'W GAZETCE TERAZ'} • ${fmt(leaf.from)}–${fmt(leaf.to)}</div><div class="hit-actions"><button data-add>+ Lista zakupów</button><button data-watch class="secondary">${watched?'★ Obserwujesz':'☆ Obserwuj to trafienie'}</button><button data-page>Pokaż stronę ${h.page}</button></div></div>`;d.querySelector('[data-add]').onclick=()=>addPageHitToCart(h,q);d.querySelector('[data-watch]').onclick=()=>toggleWatchItem(w);d.querySelector('[data-page]').onclick=()=>openViewer(leaf,h.page);root.appendChild(d)}
function enhancedRenderProducts(){const input=document.querySelector('#productSearch');if(!input)return;restoreOcrProducts();const q=input.value.trim(),sort=document.querySelector('#productSort')?.value||'priceAsc';let a=q?matchingProducts(q):PRODUCTS.filter(x=>!x.ocr);a.sort((x,y)=>sort==='priceDesc'?(y.price??-1)-(x.price??-1):sort==='unitAsc'?(x.unitPrice??999)-(y.unitPrice??999):sort==='store'?x.store.localeCompare(y.store,'pl'):(x.price??999)-(y.price??999));let hits=[];if(searchTokens(q).length){const used=new Set(a.filter(x=>!x.ocr).map(x=>`${x.leafletId}:${x.page||1}`));hits=matchingPages(q).filter(x=>!used.has(`${x.leafletId}:${x.page}`)).slice(0,30)}const info=document.querySelector('#productInfo'),root=document.querySelector('#products'),qw=q?queryWatch(q):null,watched=qw&&isWatched(qw.id);info.innerHTML=q?`${a.filter(x=>!x.ocr).length} konkretnych ofert • ${hits.length} dodatkowych trafień <button id="watchSearch" class="secondary">${watched?'✓ Obserwujesz frazę':'Obserwuj całą frazę'}</button>`:`${a.length} rozpoznanych ofert. Wyszukaj produkt i wybierz konkretną ofertę.`;document.querySelector('#watchSearch')?.addEventListener('click',()=>toggleWatchItem(qw));root.innerHTML='';a.filter(x=>!x.ocr).forEach(x=>renderProductCard(x,root));hits.forEach(h=>renderPageHit(h,q,root));if(q&&!a.filter(x=>!x.ocr).length&&!hits.length)root.innerHTML='<div class="empty">Nie znaleziono tej rzeczy. Możesz obserwować całą frazę i sprawdzić ponownie po aktualizacji gazetek.</div>';renderWatchPanel()}
const baseRenderShopping=renderShopping;renderShopping=function(){restoreOcrProducts();baseRenderShopping();document.querySelectorAll('.shop-item').forEach(row=>{if(row.textContent.includes('0,00 zł / gazetka')){const muted=row.querySelector('.muted');if(muted)muted.textContent='Cena nieodczytana • pozycja z wyszukiwarki gazetki';const strongs=row.querySelectorAll(':scope > strong');if(strongs.length)strongs[strongs.length-1].textContent='—'}});let total=0,known=0;for(const[id,qty]of Object.entries(state.cart)){const p=PRODUCTS.find(x=>x.id===id);if(p&&Number.isFinite(p.price)){total+=p.price*qty;known+=qty}}if(known<Object.values(state.cart).reduce((a,b)=>a+b,0))document.querySelector('#cartTotal').textContent=money(total)+' + pozycje bez ceny'};
const css=document.createElement('style');css.textContent=`#watchPanel{margin:18px 0 6px;padding:18px;border:1px solid #dbeafe;border-radius:16px;background:#f8fbff}.watch-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.watch-head h3{margin:0 0 4px}.watch-count{min-width:30px;height:30px;display:grid;place-items:center;border-radius:999px;background:#2563eb;color:white;font-weight:900}.watch-list{display:grid;gap:10px;margin-top:14px}.watch-card{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:14px;border:1px solid #e5e7eb;border-left:5px solid #2563eb;border-radius:12px;background:white}.watch-name{font-size:18px;font-weight:900}.watch-status{display:inline-block;margin:6px 0;padding:4px 8px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:11px;font-weight:900}.watch-meta,.watch-product{margin-top:5px;font-size:13px}.watch-actions,.hit-actions{display:flex;gap:7px;flex-wrap:wrap}.watch-empty{padding:12px;color:#64748b}.ocr-result{padding:0;overflow:hidden;display:grid;grid-template-columns:145px 1fr}.result-thumb{width:145px;height:100%;min-height:230px;object-fit:cover;object-position:top;background:#f1f5f9}.result-body{padding:15px;display:grid;gap:9px}.result-location{font-size:13px;font-weight:800;color:#475569}.result-excerpt{font-size:13px;line-height:1.45;color:#64748b;max-height:58px;overflow:hidden}.product-actions.three{display:flex;gap:7px;flex-wrap:wrap}@media(max-width:650px){.watch-card{align-items:flex-start;flex-direction:column}.watch-actions{width:100%}.watch-actions button{flex:1}.ocr-result{grid-template-columns:95px 1fr}.result-thumb{width:95px;min-height:220px}.result-excerpt{display:none}.hit-actions button{width:100%}}`;document.head.appendChild(css);
const productSearch=document.querySelector('#productSearch'),productSort=document.querySelector('#productSort');if(productSearch)productSearch.oninput=enhancedRenderProducts;if(productSort)productSort.onchange=enhancedRenderProducts;loadPageIndex();